runtime: nodejs10

env_variables:
  MONGODB_URI: "mongodb://root:MeltanAteMySp00ns@35.202.168.12:27017/nycdata"
  API_KEY_MAPBOX: 'pk.eyJ1IjoiYm5haWsyNjExIiwiYSI6ImNqdDNsOTFpNDB2aW40OXBnamtlYnRzOGUifQ.wu8BxADFpu4VHpGsSJIAgg'